'use client';

import { Sparkles } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { useDashboardNarrative } from '@/hooks/useDashboard';

/**
 * Executive-summary prose rendered at the top of the Fleet Control page.
 * LLM-generated when Anthropic is configured; falls back to a
 * deterministic template. The trust cue is explicit: if the LLM is the
 * source, the badge says "AI summary"; if it's a template, the badge
 * says "auto summary" so the user knows the difference.
 */
export function DashboardNarrative({
  section = 'fleet_overview',
}: {
  section?: string;
}) {
  const { data, isLoading, isError } = useDashboardNarrative(section);

  if (isLoading) {
    return (
      <div className="rounded-lg border bg-muted/30 p-4">
        <Skeleton className="h-16 w-full" />
      </div>
    );
  }

  if (isError || !data) {
    return null;
  }

  const badgeLabel = data.source === 'llm' ? 'AI summary' : 'auto summary';
  const badgeTone =
    data.source === 'llm'
      ? 'border-blue-500/50 text-blue-600'
      : 'border-muted-foreground/40 text-muted-foreground';

  return (
    <div className="rounded-lg border bg-muted/30 p-4">
      <div className="mb-2 flex items-center justify-between gap-3">
        <div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-muted-foreground">
          <Sparkles className="h-3.5 w-3.5" />
          Fleet overview
        </div>
        <Badge variant="outline" className={`gap-1 text-[10px] ${badgeTone}`}>
          {badgeLabel}
        </Badge>
      </div>
      <p className="text-sm leading-relaxed text-foreground">{data.narrative}</p>
      {data.model && (
        <div className="mt-1 text-[10px] text-muted-foreground">
          Generated by {data.model} ·{' '}
          {new Date(data.generated_at).toLocaleTimeString()}
        </div>
      )}
    </div>
  );
}
